GetStream/stream-chat-dart

- lib/api/channel.dart
- lib/api/responses.dart
- lib/client.dart
- lib/main.dart
- pubspec.lock
- pubspec.yaml
- Log json conversion errors using logging library (https://pub.dev/packages/logging)
- Refactoring
> Better json error logging

- lib/api/channel.dart
- lib/api/responses.dart
- lib/api/responses.g.dart
- lib/client.dart
- pubspec.lock
Add some api endpoints and response models
> Api endpoints

- lib/src/api/web_socket_channel_html.dart
- lib/src/api/web_socket_channel_io.dart
- lib/src/api/web_socket_channel_stub.dart
- lib/src/api/websocket.dart
inspired by 
- https://github.com/dart-lang/web_socket_channel/issues/64
- https://github.com/aloisdeniel/web_socket_channel/commit/658d05df461c4dfedadcde82f77defbb92849fec
> add conditional import to use websockets both on web and mobile

- lib/src/db/offline_storage.dart
- pubspec.yaml
- Removed deprecated moor_ffi dependency in favor of recommended moor/ffi.dart (as per instructions found here https://pub.dev/packages/moor_ffi)
- Ran `flutter test` to ensure that all tests were passing
> Removed moor_ffi from dependencies in favor of moor/ffi

- lib/src/client.dart
connection_id is required client side
we add it using an interceptor
> add connection id when options.data is null

- CHANGELOG.md
- lib/version.dart
- pubspec.yaml
> version bump

- lib/src/models/attachment.dart
- lib/src/models/channel_model.dart
- lib/src/models/event.dart
- lib/src/models/message.dart
- lib/src/models/own_user.dart
- lib/src/models/reaction.dart
- lib/src/models/serialization.dart
- lib/src/models/user.dart
- test/src/models/serialization_test.dart
- [☑] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required).
- [ ☑] The code changes follow best practices
- [☑ ] Code changes are tested (add some information if not applicable)
Reopening the pull request from https://github.com/GetStream/stream-chat-dart/pull/41  with tests passing
> Cleaned up Serialization on extra_data

- CHANGELOG.md
- README.md
- example/lib/generated_plugin_registrant.dart
- lib/version.dart
- pubspec.yaml
> bump version and update readme

- CHANGELOG.md
- lib/src/api/channel.dart
- lib/version.dart
- pubspec.yaml
- `Client.channel` returns an existing channel if available
- Update message in the offline storage if attachment has expired (for the new CDN)
- Fix `GetMessagesByIdResponse` format
- Do not query messages if already existing in offline storage
> bump version

- lib/src/event_type.dart
- [✅ ] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required).
- [✅ ] The code changes follow best practices
- [✅ ] Code changes are tested (add some information if not applicable)
Adds missing events related to invites
> Added missing event types for channel invites

- lib/src/api/retry_queue.dart
> fix retry queue logic

- test/version_test.dart
- Added a version test to make sure stream chat version always matches pubspec version.
> Add version test

- CHANGELOG.md
- lib/src/api/channel.dart
- lib/version.dart
- pubspec.yaml
> set message on channelupdate as optional

- CHANGELOG.md
- lib/src/api/channel.dart
- lib/version.dart
- pubspec.yaml
> add unreadcountstream

- .github/workflows/main.yml
> trigger action on every pr on every branch

- lib/src/api/channel.dart
> fix reaction event handling

- CHANGELOG.md
- lib/src/api/websocket.dart
- lib/src/client.dart
- lib/src/models/user.dart
- lib/version.dart
- pubspec.yaml
- Fix user.name getter
- Use detached loggers
- Throw error while connecting if it comes from backend
- Fix ws reconnection
> fix username getter

- CHANGELOG.md
- lib/src/api/websocket.dart
- lib/src/client.dart
- lib/version.dart
- pubspec.yaml
> do not save channel if not being watched

- CHANGELOG.md
- lib/src/db/offline_storage.dart
- lib/version.dart
- pubspec.yaml
> fix reactions with null user in offline storage

- CHANGELOG.md
- lib/src/db/offline_storage.dart
- lib/version.dart
- pubspec.yaml
> use userId for saving reactions

- .github/workflows/main.yml
- CHANGELOG.md
- lib/src/api/channel.dart
- lib/version.dart
- pubspec.yaml
> let user change channel extradata if the channel is not initialized yet

- CHANGELOG.md
- lib/src/api/channel.dart
- lib/src/client.dart
- lib/src/db/models.part.dart
- lib/src/db/offline_storage.dart
- lib/src/db/offline_storage.g.dart
- lib/src/models/message.dart
- lib/src/models/message.g.dart
- lib/version.dart
- pubspec.yaml
> feat: Added shadow bans

- lib/src/api/channel.dart
- lib/src/api/retry_queue.dart
- lib/src/client.dart
If true dispose the client state and instantiate a new one
> add clear user param to disconnect

- CHANGELOG.md
- lib/src/api/retry_queue.dart
- lib/src/client.dart
- lib/version.dart
- pubspec.yaml
> version bp

- CHANGELOG.md
- lib/src/client.dart
- lib/version.dart
- pubspec.yaml
- test/src/client_test.dart
Adds message filters into search
> Message filters

- lib/src/api/channel.dart
- test/src/api/channel_test.dart
> add enforce unique param

- lib/src/api/channel.dart
- lib/src/db/models.part.dart
- lib/src/db/offline_storage.dart
- lib/src/db/offline_storage.g.dart
> Two way pagination

- CHANGELOG.md
- lib/src/api/channel.dart
- lib/src/db/models.part.dart
- lib/src/db/offline_storage.dart
- lib/src/db/offline_storage.g.dart
- lib/src/models/member.dart
- lib/src/models/member.g.dart
- lib/version.dart
- pubspec.yaml
- Fix `channel.hide(clearHistory: true)` not clearing local messages
- Add banned field to member
> fix channel hide and truncate; add banned field in member

- CHANGELOG.md
- lib/src/db/offline_storage.dart
- lib/version.dart
- pubspec.yaml
> fix line using wrong variable

- CHANGELOG.md
- lib/src/api/channel.dart
- lib/src/models/message.dart
- lib/src/models/message.g.dart
- lib/version.dart
- pubspec.yaml
> [Message.dart] Add support for thread participants.

- CHANGELOG.md
- lib/src/client.dart
- lib/version.dart
- pubspec.yaml
- test/src/client_test.dart
> use completer to make querychannels wait for connect calls
